#pragma once
// Auto-generated by mlModel/train_export_rf_esp32.py
// Tiny RandomForest for EMPTY_RUN classification (1 = EMPTY_RUN, 0 = NORMAL)

#include <Arduino.h>

namespace EdgeRandomForest {
static constexpr int kNumFeatures = 11;
static constexpr int kNumTrees = 7;

static const char* const kFeatureNames[kNumFeatures] = {
  "rpm",
  "vibration_hz",
  "current_amp",
  "temperature_c",
  "power_factor",
  "vib_per_amp",
  "current_ratio",
  "vibration_dev",
  "temp_rise",
  "power_kw",
  "high_current_low_rpm",
};

// Tree 0
static constexpr int kTree0_NumNodes = 5;
static const int16_t kTree0_Feature[] PROGMEM = {9,-2,5,-2,-2};
static const float kTree0_Threshold[] PROGMEM = {1.07708,-2,0.368101,-2,-2};
static const int16_t kTree0_Left[] PROGMEM = {1,-1,3,-1,-1};
static const int16_t kTree0_Right[] PROGMEM = {2,-1,4,-1,-1};
static const float kTree0_Value0[] PROGMEM = {0.499059,0,1,1,1};
static const float kTree0_Value1[] PROGMEM = {0.500941,1,0,0,0};

// Tree 1
static constexpr int kTree1_NumNodes = 5;
static const int16_t kTree1_Feature[] PROGMEM = {6,-2,10,-2,-2};
static const float kTree1_Threshold[] PROGMEM = {0.551613,-2,0.5,-2,-2};
static const int16_t kTree1_Left[] PROGMEM = {1,-1,3,-1,-1};
static const int16_t kTree1_Right[] PROGMEM = {2,-1,4,-1,-1};
static const float kTree1_Value0[] PROGMEM = {0.494862,0,1,1,1};
static const float kTree1_Value1[] PROGMEM = {0.505138,1,0,0,0};

// Tree 2
static constexpr int kTree2_NumNodes = 5;
static const int16_t kTree2_Feature[] PROGMEM = {9,-2,4,-2,-2};
static const float kTree2_Threshold[] PROGMEM = {1.07708,-2,0.408,-2,-2};
static const int16_t kTree2_Left[] PROGMEM = {1,-1,3,-1,-1};
static const int16_t kTree2_Right[] PROGMEM = {2,-1,4,-1,-1};
static const float kTree2_Value0[] PROGMEM = {0.507647,0,1,1,1};
static const float kTree2_Value1[] PROGMEM = {0.492353,1,0,0,0};

// Tree 3
static constexpr int kTree3_NumNodes = 5;
static const int16_t kTree3_Feature[] PROGMEM = {2,-2,1,-2,-2};
static const float kTree3_Threshold[] PROGMEM = {8.555,-2,8.47,-2,-2};
static const int16_t kTree3_Left[] PROGMEM = {1,-1,3,-1,-1};
static const int16_t kTree3_Right[] PROGMEM = {2,-1,4,-1,-1};
static const float kTree3_Value0[] PROGMEM = {0.519772,0,1,1,1};
static const float kTree3_Value1[] PROGMEM = {0.480228,1,0,0,0};

// Tree 4
static constexpr int kTree4_NumNodes = 5;
static const int16_t kTree4_Feature[] PROGMEM = {5,5,-2,-2,-2};
static const float kTree4_Threshold[] PROGMEM = {9.76961,0.349224,-2,-2,-2};
static const int16_t kTree4_Left[] PROGMEM = {1,2,-1,-1,-1};
static const int16_t kTree4_Right[] PROGMEM = {4,3,-1,-1,-1};
static const float kTree4_Value0[] PROGMEM = {0.519519,1,1,1,0};
static const float kTree4_Value1[] PROGMEM = {0.480481,0,0,0,1};

// Tree 5
static constexpr int kTree5_NumNodes = 5;
static const int16_t kTree5_Feature[] PROGMEM = {2,-2,1,-2,-2};
static const float kTree5_Threshold[] PROGMEM = {8.555,-2,8.365,-2,-2};
static const int16_t kTree5_Left[] PROGMEM = {1,-1,3,-1,-1};
static const int16_t kTree5_Right[] PROGMEM = {2,-1,4,-1,-1};
static const float kTree5_Value0[] PROGMEM = {0.502605,0,1,1,1};
static const float kTree5_Value1[] PROGMEM = {0.497395,1,0,0,0};

// Tree 6
static constexpr int kTree6_NumNodes = 5;
static const int16_t kTree6_Feature[] PROGMEM = {2,-2,8,-2,-2};
static const float kTree6_Threshold[] PROGMEM = {8.505,-2,0.3,-2,-2};
static const int16_t kTree6_Left[] PROGMEM = {1,-1,3,-1,-1};
static const int16_t kTree6_Right[] PROGMEM = {2,-1,4,-1,-1};
static const float kTree6_Value0[] PROGMEM = {0.513521,0,1,1,1};
static const float kTree6_Value1[] PROGMEM = {0.486479,1,0,0,0};

static inline uint8_t predictOneTree(const float* features, int treeIndex) {
  int node = 0;
  while (true) {
    int16_t feature = -1;
    float threshold = 0.0f;
    int16_t left = -1;
    int16_t right = -1;

    switch (treeIndex) {
      case 0:
        feature = (int16_t)pgm_read_word(&kTree0_Feature[node]);
        threshold = pgm_read_float(&kTree0_Threshold[node]);
        left = (int16_t)pgm_read_word(&kTree0_Left[node]);
        right = (int16_t)pgm_read_word(&kTree0_Right[node]);
        break;
      case 1:
        feature = (int16_t)pgm_read_word(&kTree1_Feature[node]);
        threshold = pgm_read_float(&kTree1_Threshold[node]);
        left = (int16_t)pgm_read_word(&kTree1_Left[node]);
        right = (int16_t)pgm_read_word(&kTree1_Right[node]);
        break;
      case 2:
        feature = (int16_t)pgm_read_word(&kTree2_Feature[node]);
        threshold = pgm_read_float(&kTree2_Threshold[node]);
        left = (int16_t)pgm_read_word(&kTree2_Left[node]);
        right = (int16_t)pgm_read_word(&kTree2_Right[node]);
        break;
      case 3:
        feature = (int16_t)pgm_read_word(&kTree3_Feature[node]);
        threshold = pgm_read_float(&kTree3_Threshold[node]);
        left = (int16_t)pgm_read_word(&kTree3_Left[node]);
        right = (int16_t)pgm_read_word(&kTree3_Right[node]);
        break;
      case 4:
        feature = (int16_t)pgm_read_word(&kTree4_Feature[node]);
        threshold = pgm_read_float(&kTree4_Threshold[node]);
        left = (int16_t)pgm_read_word(&kTree4_Left[node]);
        right = (int16_t)pgm_read_word(&kTree4_Right[node]);
        break;
      case 5:
        feature = (int16_t)pgm_read_word(&kTree5_Feature[node]);
        threshold = pgm_read_float(&kTree5_Threshold[node]);
        left = (int16_t)pgm_read_word(&kTree5_Left[node]);
        right = (int16_t)pgm_read_word(&kTree5_Right[node]);
        break;
      case 6:
        feature = (int16_t)pgm_read_word(&kTree6_Feature[node]);
        threshold = pgm_read_float(&kTree6_Threshold[node]);
        left = (int16_t)pgm_read_word(&kTree6_Left[node]);
        right = (int16_t)pgm_read_word(&kTree6_Right[node]);
        break;
      default: return 0;
    }

    // Leaf
    if (feature < 0) {
      float v0 = 0.0f;
      float v1 = 0.0f;
      switch (treeIndex) {
        case 0:
          v0 = pgm_read_float(&kTree0_Value0[node]);
          v1 = pgm_read_float(&kTree0_Value1[node]);
          break;
        case 1:
          v0 = pgm_read_float(&kTree1_Value0[node]);
          v1 = pgm_read_float(&kTree1_Value1[node]);
          break;
        case 2:
          v0 = pgm_read_float(&kTree2_Value0[node]);
          v1 = pgm_read_float(&kTree2_Value1[node]);
          break;
        case 3:
          v0 = pgm_read_float(&kTree3_Value0[node]);
          v1 = pgm_read_float(&kTree3_Value1[node]);
          break;
        case 4:
          v0 = pgm_read_float(&kTree4_Value0[node]);
          v1 = pgm_read_float(&kTree4_Value1[node]);
          break;
        case 5:
          v0 = pgm_read_float(&kTree5_Value0[node]);
          v1 = pgm_read_float(&kTree5_Value1[node]);
          break;
        case 6:
          v0 = pgm_read_float(&kTree6_Value0[node]);
          v1 = pgm_read_float(&kTree6_Value1[node]);
          break;
        default: break;
      }
      return (v1 >= v0) ? 1 : 0;
    }

    const float x = features[feature];
    node = (x <= threshold) ? left : right;
    if (node < 0) return 0;
  }
}

// Returns predicted class and writes `confidence` as vote ratio for class=1 (EMPTY_RUN).
static inline uint8_t predict(const float* features, float* confidence = nullptr) {
  int votes1 = 0;
  for (int i = 0; i < kNumTrees; ++i) {
    votes1 += (int)predictOneTree(features, i);
  }
  const float conf = (float)votes1 / (float)kNumTrees;
  if (confidence) *confidence = conf;
  return (conf >= 0.5f) ? 1 : 0;
}
} // namespace EdgeRandomForest
