"""Train a tiny RandomForest model and export it as a C++ header for ESP32 inference.

This is intentionally simple (no hyperparameter search) and produces a small model
that can run on microcontrollers without external ML runtimes.

Input dataset: dataset/motor_dataset.csv (no header)
Target label: `state` column (NORMAL vs EMPTY_RUN)
Feature order: mlModel/feature_columns.json (aligned with backend feature engineering)

Usage (from repo root):
  py -3.11 mlModel/train_export_rf_esp32.py

Outputs:
  - Motor-Empty-Run-Detection-v1/include/EdgeRandomForest.h
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix


REPO_ROOT = Path(__file__).resolve().parents[1]
DATASET_PATH = REPO_ROOT / "dataset" / "motor_dataset.csv"
FEATURE_COLUMNS_PATH = REPO_ROOT / "mlModel" / "feature_columns.json"
OUT_HEADER_PATH = (
    REPO_ROOT
    / "Motor-Empty-Run-Detection-v1"
    / "include"
    / "EdgeRandomForest.h"
)


RAW_COLUMNS = [
    "timestamp_s",
    "motor_id",
    "rpm",
    "vibration_hz",
    "current_amp",
    "temperature_c",
    "power_factor",
    "state",
    "status",
    "alert_code",
]


def build_features(df: pd.DataFrame) -> pd.DataFrame:
    # Keep formulas aligned with docs/api-and-data.md and backend/src/ml/featureEngineering.js
    rpm = df["rpm"].astype(float)
    vibration_hz = df["vibration_hz"].astype(float)
    current_amp = df["current_amp"].astype(float)
    temperature_c = df["temperature_c"].astype(float)
    power_factor = df["power_factor"].astype(float)

    engineered = pd.DataFrame(index=df.index)
    engineered["rpm"] = rpm
    engineered["vibration_hz"] = vibration_hz
    engineered["current_amp"] = current_amp
    engineered["temperature_c"] = temperature_c
    engineered["power_factor"] = power_factor

    engineered["vib_per_amp"] = vibration_hz / (current_amp + 0.1)
    engineered["current_ratio"] = current_amp / 15.5
    engineered["vibration_dev"] = (vibration_hz - 60.2).abs()
    engineered["temp_rise"] = temperature_c - 48.0
    engineered["power_kw"] = (current_amp * 230.0 * power_factor) / 1000.0
    engineered["high_current_low_rpm"] = ((current_amp > 22.0) & (rpm < 200.0)).astype(float)

    return engineered


@dataclass
class ExportTree:
    feature: np.ndarray
    threshold: np.ndarray
    left: np.ndarray
    right: np.ndarray
    value0: np.ndarray
    value1: np.ndarray


def export_forest_to_header(
    model: RandomForestClassifier,
    feature_names: list[str],
    out_path: Path,
) -> None:
    trees: list[ExportTree] = []
    for estimator in model.estimators_:
        t = estimator.tree_
        # scikit stores feature=-2 for leaf
        feature = t.feature.astype(np.int16)
        threshold = t.threshold.astype(np.float32)
        left = t.children_left.astype(np.int16)
        right = t.children_right.astype(np.int16)
        values = t.value.squeeze(axis=1).astype(np.float32)  # shape: (n_nodes, n_classes)
        # binary model => classes [0,1]
        value0 = values[:, 0]
        value1 = values[:, 1]
        trees.append(
            ExportTree(
                feature=feature,
                threshold=threshold,
                left=left,
                right=right,
                value0=value0,
                value1=value1,
            )
        )

    out_path.parent.mkdir(parents=True, exist_ok=True)

    def arr_int(name: str, a: np.ndarray) -> str:
        return f"static const int16_t {name}[] PROGMEM = {{" + ",".join(map(str, a.tolist())) + "};\n"

    def arr_float(name: str, a: np.ndarray) -> str:
        # Keep reasonable precision to shrink header.
        vals = [f"{x:.6g}" for x in a.tolist()]
        return f"static const float {name}[] PROGMEM = {{" + ",".join(vals) + "};\n"

    header = []
    header.append("#pragma once\n")
    header.append("// Auto-generated by mlModel/train_export_rf_esp32.py\n")
    header.append("// Tiny RandomForest for EMPTY_RUN classification (1 = EMPTY_RUN, 0 = NORMAL)\n")
    header.append("\n")
    header.append("#include <Arduino.h>\n")
    header.append("\n")

    header.append("namespace EdgeRandomForest {\n")
    header.append(f"static constexpr int kNumFeatures = {len(feature_names)};\n")
    header.append(f"static constexpr int kNumTrees = {len(trees)};\n\n")

    # Feature names for debugging
    header.append("static const char* const kFeatureNames[kNumFeatures] = {\n")
    for n in feature_names:
        header.append(f"  \"{n}\",\n")
    header.append("};\n\n")

    # Write tree arrays
    for i, tr in enumerate(trees):
        header.append(f"// Tree {i}\n")
        header.append(f"static constexpr int kTree{i}_NumNodes = {len(tr.feature)};\n")
        header.append(arr_int(f"kTree{i}_Feature", tr.feature))
        header.append(arr_float(f"kTree{i}_Threshold", tr.threshold))
        header.append(arr_int(f"kTree{i}_Left", tr.left))
        header.append(arr_int(f"kTree{i}_Right", tr.right))
        header.append(arr_float(f"kTree{i}_Value0", tr.value0))
        header.append(arr_float(f"kTree{i}_Value1", tr.value1))
        header.append("\n")

    # Inference helper
    header.append(
        "static inline uint8_t predictOneTree(const float* features, int treeIndex) {\n"
        "  int node = 0;\n"
        "  while (true) {\n"
        "    int16_t feature = -1;\n"
        "    float threshold = 0.0f;\n"
        "    int16_t left = -1;\n"
        "    int16_t right = -1;\n"
        "\n"
        "    switch (treeIndex) {\n"
    )

    for i in range(len(trees)):
        header.append(
            f"      case {i}:\n"
            f"        feature = (int16_t)pgm_read_word(&kTree{i}_Feature[node]);\n"
            f"        threshold = pgm_read_float(&kTree{i}_Threshold[node]);\n"
            f"        left = (int16_t)pgm_read_word(&kTree{i}_Left[node]);\n"
            f"        right = (int16_t)pgm_read_word(&kTree{i}_Right[node]);\n"
            f"        break;\n"
        )

    header.append(
        "      default: return 0;\n"
        "    }\n"
        "\n"
        "    // Leaf\n"
        "    if (feature < 0) {\n"
        "      float v0 = 0.0f;\n"
        "      float v1 = 0.0f;\n"
        "      switch (treeIndex) {\n"
    )

    for i in range(len(trees)):
        header.append(
            f"        case {i}:\n"
            f"          v0 = pgm_read_float(&kTree{i}_Value0[node]);\n"
            f"          v1 = pgm_read_float(&kTree{i}_Value1[node]);\n"
            f"          break;\n"
        )

    header.append(
        "        default: break;\n"
        "      }\n"
        "      return (v1 >= v0) ? 1 : 0;\n"
        "    }\n"
        "\n"
        "    const float x = features[feature];\n"
        "    node = (x <= threshold) ? left : right;\n"
        "    if (node < 0) return 0;\n"
        "  }\n"
        "}\n\n"
    )

    header.append(
        "// Returns predicted class and writes `confidence` as vote ratio for class=1 (EMPTY_RUN).\n"
        "static inline uint8_t predict(const float* features, float* confidence = nullptr) {\n"
        "  int votes1 = 0;\n"
        "  for (int i = 0; i < kNumTrees; ++i) {\n"
        "    votes1 += (int)predictOneTree(features, i);\n"
        "  }\n"
        "  const float conf = (float)votes1 / (float)kNumTrees;\n"
        "  if (confidence) *confidence = conf;\n"
        "  return (conf >= 0.5f) ? 1 : 0;\n"
        "}\n"
    )

    header.append("} // namespace EdgeRandomForest\n")

    out_path.write_text("".join(header), encoding="utf-8")


def main() -> None:
    if not DATASET_PATH.exists():
        raise SystemExit(f"Dataset not found: {DATASET_PATH}")

    df = pd.read_csv(DATASET_PATH, header=None, names=RAW_COLUMNS)

    # Binary target: 1 = EMPTY_RUN, 0 = NORMAL
    y = (df["state"].astype(str).str.upper() == "EMPTY_RUN").astype(int)

    x_full = build_features(df)

    with FEATURE_COLUMNS_PATH.open("r", encoding="utf-8") as f:
        feature_order = json.load(f)

    x = x_full[feature_order].astype(np.float32)

    x_train, x_test, y_train, y_test = train_test_split(
        x, y, test_size=0.2, random_state=42, stratify=y
    )

    # Tiny forest: keep it small enough for ESP32
    model = RandomForestClassifier(
        n_estimators=7,
        max_depth=4,
        min_samples_leaf=5,
        random_state=42,
        class_weight="balanced",
    )
    model.fit(x_train, y_train)

    y_pred = model.predict(x_test)
    print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
    print("\nReport:\n", classification_report(y_test, y_pred, digits=4))

    export_forest_to_header(model, feature_order, OUT_HEADER_PATH)
    print(f"\nWrote: {OUT_HEADER_PATH}")


if __name__ == "__main__":
    main()
